name: Container CI/CD Pipeline

on:
  push:
    tags: ["v*.*.*"]

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  PROJECT_NAME: "hello-docker"
  CONTAINER_NAME: "github_hello-docker" 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-name: ${{ steps.process-name.outputs.safe-name }}
      image-tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Process naming
        id: process-name
        run: |
          SAFE_NAME=$(echo "$PROJECT_NAME" | 
            tr '[:upper:]' '[:lower:]' |
            sed 's/[^a-z0-9-]/-/g' |
            sed 's/-\+/-/g' |
            sed 's/^-\|-$//g')
          echo "safe-name=$SAFE_NAME" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=$SAFE_NAME" >> $GITHUB_ENV

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    env:
      CONTAINER_NAME: "github_hello-docker" # 固定容器名称

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 获取经过规范化的参数
            IMAGE_NAME="${{ needs.build-and-push.outputs.image-name }}"
            TAG="${{ needs.build-and-push.outputs.image-tag }}"
            OWNER_LOWER=$(echo "${{ env.OWNER }}" | tr '[:upper:]' '[:lower:]")

            # 构造完全合规的镜像地址
            IMAGE_REF="${{ env.REGISTRY }}/$OWNER_LOWER/$IMAGE_NAME:$TAG"

            echo "=== Deployment Parameters ==="
            echo "Final Image: $IMAGE_REF"
            echo "Container Name: $CONTAINER_NAME"

            # 容器管理流程
            echo "Pulling image..."
            docker pull $IMAGE_REF || exit 1

            echo "Removing old container..."
            docker rm -f $CONTAINER_NAME 2>/dev/null || true

            echo "Starting new container..."
            docker run -d \
              --name $CONTAINER_NAME \
              --restart unless-stopped \
              -p 3000:80 \
              $IMAGE_REF

            echo "Verifying deployment..."
            sleep 5
            docker ps -f name=$CONTAINER_NAME --format "table {{.Names}}\t{{.Status}}"
